### ISSUE TITLE
Import error (ecto_opencv.highgui)

### ISSUE THREAD

**Issue by ninafiona** [SoMa-Project/vision#48]
Ubuntu 18.04, branch: migration_1804_v2, ros melodic

I am running the second example (ifco detection). When running `plasm_yaml_ros_node.py` the error occurs:
```
rosrun ecto_rbo_yaml plasm_yaml_ros_node.py `rospack find ecto_rbo_yaml`/data/demo_ifco.yaml --debug --service 
/home/grabka/anaconda3/envs/soma/lib/python2.7/site-packages/PySide/QtGui.so: undefined symbol: _ZTI9QGtkStyle
Traceback (most recent call last):
  File "/home/grabka/Documents/SOMA/src/vision/ecto_rbo_yaml/src/plasm_yaml_ros_node.py", line 13, in <module>
    import plasm_yaml_factory
  File "/home/grabka/Documents/SOMA/src/vision/ecto_rbo_yaml/src/plasm_yaml_factory.py", line 9, in <module>
    import ecto_opencv.highgui
ImportError: /usr/lib/x86_64-linux-gnu/libcairo.so.2: undefined symbol: FT_Get_Var_Design_Coordinates
```

**Comment by zweistein** [comment]
This might be related: https://github.com/llSourcell/How_to_simulate_a_self_driving_car/issues/40

**Comment by zweistein** [comment]
https://bugs.centos.org/view.php?id=15543

**Comment by ninafiona** [comment]
The problem was the version of cairo.
```
pip install pycairo==1.18.2
conda install -c anaconda cairo
```
(second command installed version 1.14.12)
solved it.

**Comment by ninafiona** [comment]
I realized I had the wrong cairo version installed, because I installed PyQt using `conda install -c conda-forge pyqt=4.11.4`, which changed several dependent installations, including downgrading cairo.
